### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by sxyazi** [dawsers/dual-pane.yazi#1]
Thank you for creating this awesome plugin, I've been using it for a bit and already loved it! 

I have some ideas:

- Use a single status bar instead of one for each pane, as people seem to focus more on the current pane's status, and it can save some space.
- Use Yazi's active tab status without saving those states, always rendering another tab around the active one (either left or right). This could simplify the code and support scenarios with more than two tabs.
- Use the built-in `tab_switch` command directly, which cycles between tabs, still allowing for a good workflow with two tabs.
- In the README, the key bindings table excludes the `--force` option, as it can be risky and shouldn't be default behavior. Users can add it if they really want it, provided they know what they're doing.

Curious about your thoughts - if you agree, I can try to raise a PR to implement them :)

**Comment by dawsers** [comment]
Thank you! Of course it would be awesome to have your help. I discovered yazi last week, and I love it. I am moving from vifm to it, and wanted to have an environment as similar as possible to what I had, but with all the niceties and extensibility of yazi. But I am still figuring out how things work, and you are the master! So having your help in any way, either with coding, ideas, or simply being willing to answer some lingering questions would be great

>  Use a single status bar instead of one for each pane, as people seem to focus more on the current pane's status, and it  can save some space.

I agree. The only reason why this didn't happen in this first version was it was simpler to have symmetric Pane objects in the modified Root, and I didn't want the added complexity of yet another level of UI (in the code). I will definitely refactor things now that things are more or less working.

> Use Yazi's active tab status without saving those states, always rendering another tab around the active one (either left or right). This could simplify the code and support scenarios with more than two tabs.

I don't know if I understand this correctly. Do you mean I don't save the tab number where the `left` and `right` panes point to? Or do you mean there is an easier way to do what I am trying to do?

I tried to make `left` and `right` Tab objects instead of tab numbers, but pointers are not stable even from one call to context to the next, so I had to resort to numbers.

``` lua
  ya.err("Active tab: ", cx.active)
  ya.err("Active tab index in tabs: ", cx.tabs.idx)
  ya.err("Active tab in tabs: ", cx.tabs[cx.tabs.idx])
  ya.err("Number of tabs: ", #cx.tabs)
  ya.err("Tab[1]: ", cx.tabs[1])
  for i = 1, #cx.tabs do
    ya.err("Tab ", i, cx.tabs[i])
  end
```

```
"Active tab: " Tab: 0x7c5d0dea0dc8
"Active tab index in tabs: " 1
"Active tab in tabs: " Tab: 0x7c5d0dea1148
"Number of tabs: " 1
"Tab[1]: " Tab: 0x7c5d0dea1228
"Tab " 1 Tab: 0x7c5d0dea1308
```

With numbers, the code is more complicated but the indices are stable and point to whatever the context call returns that time.

I think having a stable inactive pane is useful. I store left and right so things *freeze* when one pane becomes inactive, but I still want to make it active in the future or use it as destination to copy files to. This adds code complexity when adding a new tab, but the pointer solution didn't work.
 
> Use the built-in `tab_switch` command directly, which cycles between tabs, still allowing for a good workflow with two tabs.

As I use numbers for left/right state, I still need some book keeping, or it could be I still don't understand what you mean.

> In the README, the key bindings table excludes the `--force` option, as it can be risky and shouldn't be default behavior. Users can add it if they really want it, provided they know what they're doing.

You are right, I just copied my config, but I will change that to make it less risky.

Please, let me know what I am missing, I would love to make the code simpler. 

I also have a question for you. In the current state of the code, when I insert a new tab, the order of files in the inactive pane changes to something random. It is very noticeable because I use `mtime` sorting, and as soon as I insert the tab, the inactive pane (which was keeping the proper order), suddenly changes its sorting to something that appears to be random. I made a comment in the code, but couldn't figure out how to fix it. As soon as I switch to the inactive pane, it performs the correct sorting, but not before I do. I figured it could be related to the way `ya.manager_emit()` works, but I couldn't find a workaround.

**Comment by dawsers** [comment]
I changed the README to remove `--force`, and the UI to include only the status bar of the active pane.

**Comment by sxyazi** [comment]
Thanks for the response and change!

> but pointers are not stable even from one call to context to the next, so I had to resort to numbers

Ah, this is a real issue, I can add a field in Yazi to represent the unique ID of the tab.

> As I use numbers for left/right state, I still need some book keeping, or it could be I still don't understand what you mean.

I'll implement and raise a PR shortly, I can explain the code there.

> I made a comment in the code, but couldn't figure out how to fix it

Can you link to that code?

**Comment by dawsers** [comment]
> > I made a comment in the code, but couldn't figure out how to fix it
> 
> Can you link to that code?

https://github.com/dawsers/dual-pane.yazi/blob/d01bbde59a2bd74117db8aa0f4c8cedd7d6967ac/init.lua#L390

My feeling is a tab doesn't get sorted until it is active, so the inactive pane loses its sorting when the user creates a new tab. 

I use `sort_by = "mtime"`

The bug goes like this: creating a new tab when both panes are showing the same tab, switches the active pane to the new tab, while the inactive one still shows the original one...but loses its sorting until it is active again.

**Comment by dawsers** [comment]
Closed with https://github.com/dawsers/dual-pane.yazi/pull/2
